### ISSUE TITLE
spectacular: is it possible to see if an Injector has been called?

### ISSUE THREAD

**Issue by matheo** [ngworker/ngworker#24]
## Describe the solution you'd like

Spectator has a possibility to do something like this:
`expect(spectator.inject(ApplicationAPIService).getAttachments).toHaveBeenCalled()` 

I'm not familiarwith the `@testing-library` yet, so I hope there's a way to fulfill this one.
Thanks in advance!

**Comment by matheo** [comment]
I imagine that `provideStore` from `@ngrx/store/testing` works without issues too right?
I've checked the `spectacular-example-angular-testing-library` but it's kinda too simple :thinking:

**Comment by LayZeeDK** [comment]
Hi @matheo

You need to replace `ApplicationAPIService#getAttachments` with a spy to be able to use `expect(someSpy).toHaveBeenCalled()`.

For example using Jest:
```ts
// Arange
const apiService = harness.inject(ApplicationAPIService);
const getAttachmentsSpy = jest.spyOn(apiService, 'getAttachments');

// Act
// Click a button, navigate to a page or something like that

// Assert
expect(getAttachmentsSpy).toHaveBeenCalled();
```

**Comment by LayZeeDK** [comment]
> I imagine that provideStore from `@ngrx/store/testing` works without issues too right?

Yes, add it to the `providers` option of a `create*Harness` function.

**Comment by matheo** [comment]
@LayZeeDK I'm having troubles figuring out how to:

1. Provide my feature module
2. Create a Harness/TestBed for a single component of it
3. Retrieve  my injected mocks to check if `HaveBeenCalled`
4. Dispatch a Store action
5. Trigger an action in my Component / click the Save button
6. Click and Fill some controls in a Form
7. Validate some error messages shown in the Control

I've checked the `spec` files of the library but they uses different approaches that doesn't cover all these items together :(
TIA

**Comment by LayZeeDK** [comment]
>  have no experience with Harnesses and I'm not sure how to createFeatureHarness (@ngworker/spectacular) to be able to harness.inject and get my providers,

`Spectacular*Harness#inject` calls  `TestBed.inject` directly. It's just a convenience API. You can pass `providers` and/or `imports` to most of the `create*Harness` functions.

> render (@testing-library/angular) to be able to detectChanges and access the component via result.fixture.componentInstance. Or they are not supposed to be used at the same time? it seems that I need to understand what's happening under the hood to know when to use them.

Learn Angular Testing Library, use Component Harnesses, or use the native TestBed.

Did you watch some of the Spectacular videos?

https://youtu.be/2GYD594kN4s

https://youtu.be/VK2tQDJiv4s

I know we need docs. I just haven't figured out a setup for a docs website yet.

**Comment by LayZeeDK** [comment]
Here's an example repo https://github.com/LayZeeDK/spectacular-example-angular-testing-library
