### ISSUE TITLE
spectacular: Support for Angular 13

### ISSUE THREAD

**Issue by meirka** [ngworker/ngworker#31]
## What is the motivation/use case for changing the behavior?

No change to behavior

## Describe the solution you'd like

```npm install --save-dev @ngworker/spectacular``` - installs as dev dependency

## Describe alternatives you've considered

Haven't considered any alternatives at the moment

## Additional context

npm ERR! Found: @angular/common@13.1.3
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^13.1.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^11.0.9" from @ngworker/spectacular@0.2.0
npm ERR! node_modules/@ngworker/spectacular
npm ERR!   dev @ngworker/spectacular@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by LayZeeDK** [comment]
Hey, thanks for giving feedback. Spectacular works with Angular 13.x even though it complains. We're just not verifying every major version in CI yet. Which is the only reason it's still marked as v0.x.

**Comment by LayZeeDK** [comment]
I'm happy to announce that official Angular 13 support is out with the Spectacular 13 release https://github.com/ngworker/ngworker/releases/tag/spectacular-v13.0.0

Fixed by #57.
